### ISSUE TITLE
Unnecessary dependency to Microsoft.WindowsAppSDK in Windows.Api.Helpers.csproj

### ISSUE THREAD

**Issue by henrik-db** [distributed-medical/VidiView_OpenAPI#1]
Please remove :-)

	<ItemGroup Condition="'$(TargetFramework)'=='net7.0-windows10.0.17763.0'">
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.4.231115000" />
	</ItemGroup>

**Comment by bjorn-malmo** [comment]
Fixed
